### ISSUE TITLE
how to check if a Elem is Enum type?

### ISSUE THREAD

**Issue by shengdoushi** [YYCoder/thrifter#1]
now , enum's Type is FIELD_TYPE_IDENT. So how to check if its a enum type.

service RoleService {

    RoleInfo getRoleByStatus(1:RoleStatus status)
}

**Comment by YYCoder** [comment]
Hi, @shengdoushi, you can make a type assertion with the `Node` interface, as each AST element has implemented the `Node` interface, or you can call the `NodeType` method on the `Node`, it will return a string "Enum".

```go
type Node interface {
	// recursively output current node and its children
	String() string
	// recursively parse current node and its children
	parse(p *Parser) error
	// get node value
	NodeValue() interface{}
	// get node type, value specified from each node
	NodeType() string
}
```

**Comment by YYCoder** [comment]
BTW, I just saw your fork of [protobuf-thrift](https://github.com/shengdoushi/protobuf-thrift), there are some amazing features you have made, I really hope you can make a PR to it.😁
